services:
  mysql:
    image: mysql:8.0
    container_name: Mysqlbref
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cinemaDB
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3305:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminbref
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8087:80"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpoop
    restart: always
    volumes:
      - ./app:/var/www/html
    ports:
      - "86:80"

volumes:
  mysql_data: