services:
  mysql:
    image: mysql:8.0
    container_name: Mysqloop
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: cinema
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3301:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminoop
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8083:80"

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phpoop
    restart: always
    volumes:
      - ./project:/var/www/html
    ports:
      - "84:80"

volumes:
  mysql_data: